name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.5.4
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.21.0      # the core CARP domain model

  signature: ^2.0.0 # ^3.2.0
  rxdart: ^0.25.0
  json_annotation: ^3.1.0
  flutter_localizations:
    sdk: flutter
  collection: ^1.14.11
  flutter_i18n: ^0.22.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_core:
#    path: ../carp/carp.sensing-flutter/carp_core/

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.5.0
#  test: ^1.14.3
  test: 

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/analysis.png
    - assets/icons/archive.png
    - assets/icons/deadline.png
    - assets/icons/document.png
    - assets/icons/handshake.png
    - assets/icons/id.png
    - assets/icons/management.png
    - assets/icons/networking.png
    - assets/icons/settings.png
    - assets/icons/target.png
    - assets/icons/id.png
    # To add assets to the package, add an assets inside lib, like this:
    - lib/lang/en.json
    - lib/lang/da.json
#    - assets/lang_2/da.json
#    - assets/lang_2/en.json

  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
